config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  resources :skiresorts, only: %i[index]
  resources :parks, only: %i[index show]
  resources :users, only: %i[show edit update]
  resources :lanes, only: %i[create update destroy]
  resources :inquiries, only: %i[new create]
  resources :comments, only: %i[create destroy] do
    resources :likes, only: %i[create destroy]
  end

  get '/skiresorts/search', to: 'skiresorts#search'
  get 'auth/:provider/callback', to: 'sessions#callback'
  get '/logout', to: 'sessions#destroy'
  get '/login', to: 'static_pages#login'

  namespace :api, { format: 'json' } do
    namespace :v1 do
      resources :skiresorts
      resources :parks
      resources :users
      resources :lanes
      resources :inquiries
    end
  end

end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :comment, counter_cache: :like_count
  belongs_to :user

  validates_uniqueness_of :comment_id, scope: :user_id

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  before_action :logged_in_user?, only:[:create, :destroy]
  before_action :correct_user?, only: [:create, :destroy]

  def create
    Like.create(user_id: current_user.id, comment_id: params[:comment_id])
    @likes = Like.where(comment_id: params[:comment_id])
    @comment = Comment.find(params[:comment_id])
    respond_to do |format|
      format.js
    end
  end

  def destroy
    Like.find_by(comment_id: params[:comment_id], user_id: current_user.id).destroy
    @likes = Like.where(comment_id: params[:comment_id])
    @comment = Comment.find(params[:comment_id])
    respond_to do |format|
      format.js
    end
  end

end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_like.html.slim
- if current_user.nil?
  = fa_icon "thumbs-up"
  = comment.like_count
- else
  - if comment.like_user?(current_user.id)
    = link_to (fa_icon "thumbs-up", text: comment.like_count ), comment_like_path(likes, comment_id: comment.id), method: :delete, class: "text-primary", remote: true
  - else
    = link_to (fa_icon "thumbs-up", text: comment.like_count ), comment_likes_path(comment), method: :post, class: "text-secondary", remote: true

app/views/likes/create.js.erb
$("#comment-<%= @comment.id %> .like-btn").html("<%= j(render :partial => 'likes/like', locals: {comment: @comment, likes: @likes}) %>");

app/views/likes/destroy.js.erb
$("#comment-<%= @comment.id %> .like-btn").html("<%= j(render :partial => 'likes/like', locals: {comment: @comment, likes: @likes}) %>");