config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  resources :skiresorts, only: %i[index]
  resources :parks, only: %i[index show]
  resources :users, only: %i[show edit update]
  resources :lanes, only: %i[create update destroy]
  resources :inquiries, only: %i[new create]
  resources :comments, only: %i[create destroy] do
    resources :likes, only: %i[create destroy]
  end

  get '/skiresorts/search', to: 'skiresorts#search'
  get 'auth/:provider/callback', to: 'sessions#callback'
  get '/logout', to: 'sessions#destroy'
  get '/login', to: 'static_pages#login'

  namespace :api, { format: 'json' } do
    namespace :v1 do
      resources :skiresorts
      resources :parks
      resources :users
      resources :lanes
      resources :inquiries
    end
  end

end

app/models/lane.rb
# == Schema Information
#
# Table name: lanes
#
#  id         :integer          not null, primary key
#  name       :string
#  items      :text
#  park_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer
#

class Lane < ApplicationRecord
  belongs_to :park
  belongs_to :user

  validates :name, presence: true
  validates :items, presence: true
  validates :park_id, presence: true
  validates :user_id, presence: true

end

app/controllers/lanes_controller.rb
class LanesController < ApplicationController

  before_action :logged_in_user?
  before_action :correct_user?, only: :destroy

  def create
    @lane = Park.find(params[:park_id]).lanes.build(lane_params)
    if @lane.save
      flash[:info] = "レーンを反映しました。"
      redirect_to @lane.park
    else
      flash[:info] = "レーンの反映に失敗しました。"
      redirect_to @lane.park
    end
  end

  def update
    @lane = Lane.find(params[:lane_id])
    if @lane.update_attributes(lane_params)
      flash[:info] = 'レーンを反映しました'
      redirect_to @lane.park
    else
      flash[:info] = "レーンの反映に失敗しました。"
      redirect_to @lane.park
    end
  end

  def destroy
    Lane.find(params[:id]).destroy
    flash[:info] = "レーンを削除しました。"
    redirect_to request.referrer || root_url
  end

  private

  def lane_params
    params.require(:lane).permit(:name, :items, :user_id)
  end

end

app/helpers/lanes_helper.rb
module LanesHelper
end

app/views/lanes/_lane.html.slim
.each-lane.bg-light.p-3.mb-4
  .name.border-bottom.mb-1 = lane.name
  .items = lane.items
  - if session[:user_id].present?
    a.text-dark data-target=("#modal-#{lane.id}") data-toggle="modal" href="#" = fa_icon "edit"
    = link_to (fa_icon "trash"), lane, method: :delete, data: { confirm: "本当に削除しますか?" }, class: "text-dark pl-1"
    = link_to (image_tag(lane.user.profile_image, {alt: "profile_pic", height: 60, class: "rounded"})), lane.user, class: "lane-user"

.modal.fade aria-labelledby="myModalLabel" id=("modal-#{lane.id}") role="dialog" tabindex="-1"
  .modal-dialog role="document"
    .modal-content
      .modal-header
        = lane.name
        = lane.items
        h5#exampleModalLabel.modal-title レーンを編集
        button.close aria-label="閉じる" data-dismiss="modal" type="button"
          span aria-hidden="true" &times;
      .modal-body
        .lane-form
          = form_for lane, :url => lane_path do |f|
            = hidden_field_tag :lane_id, lane.id
            = f.hidden_field :user_id, :value => session[:user_id]
            = render 'shared/error_messages', object: f.object
            .items-form
              = f.label "名前を変更"
              = f.text_field :name, class: 'form-control', required: true, placeholder: lane.name
            .items-form.mt-2
              = f.label "レイアウトを変更"
              = f.text_area :items, class: 'form-control', required: true, placeholder: lane.items
            .modal-footer
              = f.submit "更新する", class: "btn btn-info"
              button.btn.btn-outline-info data-dismiss="modal" type="button"  閉じる

app/views/lanes/_lane_form.html.slim
button.btn.btn-outline-info.btn-block.rounded-0 data-target="#createModal" data-toggle="modal" type="button" レーンを追加する
#createModal.modal.fade aria-labelledby="myModalLabel" role="dialog" tabindex="-1"
  .modal-dialog role="document"
    .modal-content
      .modal-header
        h5#exampleModalLabel.modal-title レーンを追加
        button.close aria-label="閉じる" data-dismiss="modal" type="button"
          span aria-hidden="true" &times;
      .modal-body
        .lane-form
          - @lane ||= Lane.new
          = form_for @lane do |f|
            = hidden_field_tag :park_id, park.id
            = f.hidden_field :user_id, :value => session[:user_id]
            = render 'shared/error_messages', object: f.object
            .items-form
              = f.label "名前を入力"
              = f.text_field :name, class: 'form-control', required: true, placeholder: "例:上級レーン"
            .items-form.mt-2
              = f.label "レイアウトを紹介"
              = f.text_area :items, class: 'form-control', required: true, placeholder: "レイアウトを入力"
            .modal-footer
              = f.submit "追加する", class: "btn btn-info"
              button.btn.btn-outline-info data-dismiss="modal" type="button"  閉じる