config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  resources :skiresorts, only: %i[index]
  resources :parks, only: %i[index show]
  resources :users, only: %i[show edit update]
  resources :lanes, only: %i[create update destroy]
  resources :inquiries, only: %i[new create]
  resources :comments, only: %i[create destroy] do
    resources :likes, only: %i[create destroy]
  end

  get '/skiresorts/search', to: 'skiresorts#search'
  get 'auth/:provider/callback', to: 'sessions#callback'
  get '/logout', to: 'sessions#destroy'
  get '/login', to: 'static_pages#login'

  namespace :api, { format: 'json' } do
    namespace :v1 do
      resources :skiresorts
      resources :parks
      resources :users
      resources :lanes
      resources :inquiries
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  park_id    :integer
#  body       :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  like_count :integer          default(0)
#

class Comment < ApplicationRecord
  belongs_to :user, counter_cache: :comment_count
  belongs_to :park, counter_cache: :comment_count
  has_many :likes, dependent: :destroy

  validates :body, presence: true, length: { maximum: 255 }

  # いいねしているユーザーかどうか
  def like_user?(user_id)
    !likes.find_by(user_id: user_id).blank?
  end

end

app/models/inquiry.rb
# == Schema Information
#
# Table name: inquiries
#
#  id         :integer          not null, primary key
#  name       :string
#  email      :string
#  content    :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Inquiry < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true
  validates :content, presence: true

  def send_user_inquiry
    InquiryMailer.user_inquiry(self).deliver
  end
end

app/models/lane.rb
# == Schema Information
#
# Table name: lanes
#
#  id         :integer          not null, primary key
#  name       :string
#  items      :text
#  park_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer
#

class Lane < ApplicationRecord
  belongs_to :park
  belongs_to :user

  validates :name, presence: true
  validates :items, presence: true
  validates :park_id, presence: true
  validates :user_id, presence: true

end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :comment, counter_cache: :like_count
  belongs_to :user

  validates_uniqueness_of :comment_id, scope: :user_id

end

app/models/park.rb
# == Schema Information
#
# Table name: parks
#
#  id            :integer          not null, primary key
#  name          :string
#  comment_count :integer          default(0)
#  area_id       :integer
#  skiresort_id  :integer
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  picture       :string
#  description   :text
#

class Park < ApplicationRecord

  has_many :comments, dependent: :destroy
  has_many :lanes, dependent: :destroy
  belongs_to :skiresort,counter_cache: :park_count

  validates :name, presence: true
  validates :area_id, presence: true
  validates :skiresort_id, presence: true
  validates :description, presence: true

end

app/models/skiresort.rb
# == Schema Information
#
# Table name: skiresorts
#
#  id          :integer          not null, primary key
#  name        :string
#  prefecture  :string
#  area_id     :integer
#  park_count  :integer          default(0)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  sas_url     :string
#  picture     :string
#  description :text
#

class Skiresort < ApplicationRecord

  has_many :parks, dependent: :destroy

  scope :have_parks, -> {where.not(park_count: 0)}

  validates :name, presence: true
  validates :prefecture, presence: true
  validates :area_id, presence: true
  validates :sas_url, presence: true
  validates :description, presence: true

  # スクレイピングにより"Surf and snow"から積雪量とゲレンデ状況を得るインスタンスメソッド
  def getGelaendeCondition
    agent = Mechanize.new
    page = agent.get(self.sas_url)
    elements = page.search('td.bottom em')
    snowfall = "不明"
    range = "不明"
    snowfall = elements[0].inner_text if elements[0].present?
    range = elements[2].inner_text if elements[2].present?
    return {"snowfall" => snowfall + "cm", "range" => range}
  end

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                :integer          not null, primary key
#  name              :string
#  age               :integer
#  gender            :integer
#  area_id           :integer
#  image             :string
#  comment_count     :integer          default(0)
#  provider          :string
#  uid               :string
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  self_introduction :text
#  home_gelaende     :string
#

class User < ApplicationRecord

  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :lanes, dependent: :destroy

  mount_uploader :image, ImageUploader

  validates :name, presence: true, length: { maximum: 30 }
  validates :self_introduction, length: { maximum: 140 }
  validates :home_gelaende, length: { maximum: 20 }
  enum gender: { male: 0, female: 1 }

  def self.create_with_facebook(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["info"]["name"]
      user.area_id = 0
    end
  end

  def profile_image
    self.image.blank? ? "profile_pic.jpeg" : self.image
  end

end

app/controllers/lanes_controller.rb
class LanesController < ApplicationController

  before_action :logged_in_user?
  before_action :correct_user?, only: :destroy

  def create
    @lane = Park.find(params[:park_id]).lanes.build(lane_params)
    if @lane.save
      flash[:info] = "レーンを反映しました。"
      redirect_to @lane.park
    else
      flash[:info] = "レーンの反映に失敗しました。"
      redirect_to @lane.park
    end
  end

  def update
    @lane = Lane.find(params[:lane_id])
    if @lane.update_attributes(lane_params)
      flash[:info] = 'レーンを反映しました'
      redirect_to @lane.park
    else
      flash[:info] = "レーンの反映に失敗しました。"
      redirect_to @lane.park
    end
  end

  def destroy
    Lane.find(params[:id]).destroy
    flash[:info] = "レーンを削除しました。"
    redirect_to request.referrer || root_url
  end

  private

  def lane_params
    params.require(:lane).permit(:name, :items, :user_id)
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  before_action :logged_in_user?, only:[:create, :destroy]
  before_action :correct_user?, only: [:create, :destroy]

  def create
    Like.create(user_id: current_user.id, comment_id: params[:comment_id])
    @likes = Like.where(comment_id: params[:comment_id])
    @comment = Comment.find(params[:comment_id])
    respond_to do |format|
      format.js
    end
  end

  def destroy
    Like.find_by(comment_id: params[:comment_id], user_id: current_user.id).destroy
    @likes = Like.where(comment_id: params[:comment_id])
    @comment = Comment.find(params[:comment_id])
    respond_to do |format|
      format.js
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/inquiries_helper.rb
module InquiriesHelper
end

app/helpers/lanes_helper.rb
module LanesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/parks_helper.rb
module ParksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def current_user
    return unless session[:user_id]
    @current_user ||= User.find(session[:user_id])
  end

  def logged_in?
    !session[:user_id].nil?
  end

  def current_user?(user)
    user == current_user
  end

  def redirect_back_or(default)
    redirect_to(session[:forwording_url] || default)
    session.delete(:forwording_url)
  end

  def store_location
    session[:forwording_url] = request.original_url if request.get?
  end
  
end

app/helpers/skiresorts_helper.rb
module SkiresortsHelper

  # ヘッダーからのスキー場検索で用いる
  def searchSkiresorts(query)
    if query
      Skiresort.where(['name LIKE ?', "%#{query}%"])
    else
      Skiresort.all
    end
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.slim
footer.mt-3.py-3.text-center.border-top-gray
  small
    | Copyright© 
    a.text-dark href="https://github.com/kotaroooo0" kotaroooo0
    |. All rights reserved.

app/views/layouts/_header.html.slim
nav.navbar.navbar-expand-lg.navbar-dark.mb-3.bg-info
  = link_to (fa_icon "product-hunt", class: "fa-lg") + "ARKINDEX", root_path, class: "navbar-brand"
  button.navbar-toggler aria-controls="Navber" aria-expanded="false" aria-label="ナビゲーションの切替" data-target="#Navber" data-toggle="collapse" type="button"
    span.navbar-toggler-icon
  #Navber.collapse.navbar-collapse
    ul.navbar-nav.mr-auto
      li class=("nav-item #{'active' if (controller.controller_name + controller.action_name) == 'static_pageshome'}")
        = link_to "ホーム", root_path, class: "nav-link"
      li class=("nav-item dropdown #{'active' if (controller.controller_name + controller.action_name) == 'skiresortsindex'}")
        a#navbarDropdown.nav-link.dropdown-toggle aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" href="#" role="button" スキー場
        .dropdown-menu aria-labelledby="navbarDropdown"
          - Constants::Area.all.each do |area|
            - next if area.name == "未設定"
            = link_to "#{area.name}エリア", skiresorts_path(area_id: area.id), class: "dropdown-item"
      li class=("nav-item dropdown #{'active' if (controller.controller_name + controller.action_name) == 'parksindex'}")
        a#navbarDropdown.nav-link.dropdown-toggle aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" href="#" role="button" パーク
        .dropdown-menu aria-labelledby="navbarDropdown"
          - Constants::Area.all.each do |area|
            - next if area.name == "未設定"
            = link_to "#{area.name}エリア", parks_path(area_id: area.id), class: "dropdown-item"
      li class=("nav-item #{'active' if (controller.controller_name + controller.action_name) == 'inquiriesnew'}")
        = link_to "お問い合わせ", new_inquiry_path, class: "nav-link"
      - if logged_in?
        li class=("nav-item dropdown #{'active' if controller.controller_name == 'users'}")
          a#navbarDropdown.nav-link.dropdown-toggle aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" href="#" role="button" アカウント
          .dropdown-menu aria-labelledby="navbarDropdown"
            = link_to "プロフール詳細",current_user, class: "dropdown-item"
            = link_to "プロフィール編集",edit_user_path(current_user), class: "dropdown-item"
            .dropdown-divider
            = link_to "ログアウト",logout_path, class: "dropdown-item"
      - else
        li.nav-item.if class=("<%= 'active' (controller.controller_name + controller.action_name) == 'static_pageslogin' %>")
          = link_to "ログイン",login_path, class: "nav-link"
    = form_tag skiresorts_search_path, method: :get, class: "form-inline" do
      .input-group
        = text_field_tag(:search, params[:search], placeholder: "スキー場を入力", class: "form-control", "aria-describedby" => "addon")
      .input-group-append
        = submit_tag "検索", id: "addon", class: "btn btn-outline-info bg-light"

app/views/layouts/application.html.slim
doctype html
html
  head
    title ParkIndex
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = render 'layouts/header'
    .container
      - flash.each do |message_type, message|
        = content_tag(:div, message, class: "alert alert-#{message_type}")
      = yield
      = render 'layouts/footer'

app/views/shared/_error_messages.html.slim
- if object.errors.any?
  #error_explanation
    .alert.alert-danger
      = object.errors.count
      | 件のエラーがあります
    ul
      - object.errors.full_messages.each do |msg|
        li = msg